evaluation:

    Output: 0

    Final_Score_Kinematics: 0.0

    Final_Score_EMG: 0.0

    rest_energy:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

    Code_ID_patient: 'codice_id_paziente'

    Patient_Name: 'Name'

    Patient_Surname: 'Surname'

    Flag_start_eval: false

    Flag_end_eval: false

    Path_pdf: 'name_pdf'

    Path_emg_pdf: 'emg_name_pdf'

    Flag_start_eval_emg: false

    Flag_end_eval_emg: false

    CSVEMG: 'csvemg'

    CSVKinematics: 'csvkin'



