registration_antenna_point:
  - 0.0
  - 0.0
  - 0.0

registration_matrix:
  - 0.0
  - 0.0
  - 0.0

active_modules:
  - true   # SPALLA 0
  - true   # GOMITO 1
  - true   # POLSO 2
  - true   # MAT 3
  - false   # RF SYSTEM 4
  - false   # EMG/EEG 5
  - false   # MAP 6
  - false   # JOYSTICK 7
  - false   # VOCAL 8
  - false   # IK ONLINE

side: false #FALSE = sx, TRUE = dx

scenario: 0





